spring:
  batch.job.enabled: false # CommandLineRunner 설정 해제
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  h2:
    console:
      enabled: true
  session:
    store-type: jdbc

