spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: lovethefeel
    password: qwer1234
    url: jdbc:mysql://localhost:3306/TESTDB

  jpa:
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: none

  redis:
    pool:
      max:
        active: 60
        idle: 60
      min:
        idle: 10
      wait:
        milli: 200
    host: localhost
    port: 6379

logging:
  level:
    org.hibernate.type.descriptor.sql: trace