spring:
  redis:
    pool:
      max:
        active: 60
        idle: 60
      min:
        idle: 10
      wait:
        milli: 200
    host: localhost
    port: 6379

logging:
  level:
    org.hibernate.type.descriptor.sql: trace