security:
  jwt:
    token:
      secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno
      expire-length: 3600000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: lovethefeel
    password: qwer1234
    url: jdbc:mysql://localhost:3306/TESTDB

  jpa:
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: none

logging:
  level:
    org.hibernate.type.descriptor.sql: trace