#Database
#Database 설정 필요
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/testdb?rewriteBatchedInserts=true
    username: admin
    password: passwd

    #Connection Pool
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      data-source-properties:
        rewriteBatchedStatements: true

  #JPA
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
    properties:
      hibernate:
        jdbc.batch_size: 100
        order_inserts: true
        order_updates: true


