POST http://localhost:8080/users
Content-Type: application/json

{
  "user_id": "test",
  "user_name": "test",
  "sex": "MALE",
  "mobile_agency": "SK",
  "phone1": "010",
  "phone2": "1111",
  "phone3": "2222"
}