spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
    show-sql: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace